# Generated by Django 3.0.8 on 2020-07-24 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(choices=[('GR', 'General'), ('SP', 'Support'), ('AS', 'Assignment'), ('EX', 'Examination'), ('PR', 'Practical')], default='GR', max_length=2)),
                ('body', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='mail/{sender_id}/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sender_starred', models.BooleanField(default=False)),
                ('sender_delete', models.BooleanField(default=False)),
                ('mail_draft', models.BooleanField(default=False)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyEmail.Mail')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mail_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MailReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('viewed_date', models.DateTimeField(blank=True, null=True)),
                ('mail_starred', models.BooleanField(default=False)),
                ('mail_spam', models.BooleanField(default=False)),
                ('mail_deleted', models.BooleanField(default=False)),
                ('mail_viewed', models.BooleanField(default=False)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyEmail.Mail')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
