# Generated by Django 3.0.8 on 2020-07-21 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyEmail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailreceiver',
            old_name='email',
            new_name='mail',
        ),
    ]
