# Generated by Django 3.0.8 on 2020-07-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEmail', '0002_auto_20200724_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailreceiver',
            name='viewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
