# Generated by Django 3.0.8 on 2020-07-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyEmail', '0002_auto_20200721_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='mail_draft',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='sender_delete',
        ),
    ]
