# Generated by Django 3.0.8 on 2020-07-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEmail', '0003_auto_20200721_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mail_draft',
            field=models.BooleanField(default=False),
        ),
    ]
