# Generated by Django 3.0.8 on 2020-07-24 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyEmail', '0003_auto_20200724_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='reply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyEmail.Mail'),
        ),
    ]
