# Generated by Django 3.0.8 on 2020-07-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEmail', '0004_mail_mail_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailreceiver',
            old_name='send_date',
            new_name='received_date',
        ),
        migrations.RemoveField(
            model_name='mailreceiver',
            name='mail_send',
        ),
        migrations.AddField(
            model_name='mail',
            name='sender_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='sender_starred',
            field=models.BooleanField(default=False),
        ),
    ]
