# Generated by Django 3.0.8 on 2020-07-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyEmail', '0005_auto_20200724_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='label',
            field=models.CharField(blank=True, choices=[('GR', 'General'), ('SP', 'Support'), ('AS', 'Assignment'), ('EX', 'Examination'), ('PR', 'Practical')], default='GR', max_length=2),
        ),
    ]
